
version: '3.3'

services:

  sam-abee-proxy:
    restart: on-failure
    build: ./
    working_dir: /Users/samjohnson/Documents/hrfiles/petco/nick-proxy-server
    ports:
      - "80:3000"
    command: bash -c "npm install && npm start"
    volumes:
      - ./:/Users/samjohnson/Documents/hrfiles/petco/nick-proxy-server